language: r
sudo: false
cache: packages

matrix:
  include:
    - r: release
      env: DEPS=cran
      os: linux
    - r: release
      env: DEPS=cran
      os: osx
    - r: oldrel
      env: DEPS=cran
      os: linux
    - r: oldrel
      env: DEPS=cran
      os: osx
    - r: devel
      env: DEPS=cran
      os: linux
    - r: devel
      env: DEPS=cran
      os: osx


r_packages:
  - covr

notifications:
    email:
      on_success: change
      on_failure: change

after_success:
  - Rscript -e 'library(covr); codecov()'

env:
- LINTR_COMMENT_BOT=false
